-- MySQL Script generated by MySQL Workbench
-- Wed Sep  2 15:54:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_pizzaria_sa
-- -----------------------------------------------------
-- Banco de dados de um site de pizzaria.

-- -----------------------------------------------------
-- Schema db_pizzaria_sa
--
-- Banco de dados de um site de pizzaria.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pizzaria_sa` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria_sa` ;

-- -----------------------------------------------------
-- Table `db_pizzaria_sa`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_sa`.`usuarios` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(12) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria_sa`.`sabores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_sa`.`sabores` (
  `codigo` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` TEXT NOT NULL,
  `tipo` TINYINT(3) UNSIGNED NOT NULL COMMENT '0 = Doce, 1 = Salgado',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria_sa`.`tamanhos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_sa`.`tamanhos` (
  `id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(12) NOT NULL,
  `preco` DECIMAL(4,2) NOT NULL,
  `fatias`SMALLINT(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
